### ISSUE TITLE
feat(`parseEventDeclaration`): improve formatting detection

### ISSUE THREAD

**Issue by tcoratger** [grindery-io/grindery-nexus-connector-web3#103]
In the regex that dispatches the different parts of the event signature, it doesn't need to have the `event` prefix at the start at the moment. This can lead to inconsistencies.

For example, if by mistake, in the signature, the name of the event is forgotten (`event (address previousAdmin, address newAdmin);`), the parser considers `event` as the name of the event and therefore the trigger will never detect the event in question which does not exist.

So I suggest that the `event` prefix be mandatory (it could also be totally removed, but it's mostly present and it adds more meaning in the signature writing) at the beginning. In this way there can be no ambiguity. And if the `event` prefix is not present then the `Invalid event declaration` error is thrown.

**Comment by SAPikachu** [comment]
Please check my comment at https://github.com/grindery-io/grindery-nexus-connector-web3/issues/106#issuecomment-1655402630 , applies here as well.
