### ISSUE TITLE
refactor(`sanitizeParameters`): simplification of `paramKeys`

### ISSUE THREAD

**Issue by tcoratger** [grindery-io/grindery-nexus-connector-web3#112]
Is there any particular use in leaving `paramKeys` as a parameter to the `sanitizeParameters` function? 

I see that in all calls to `sanitizeParameters` this optional parameter filled by default by `["parameterFilters", "parameters"]` is never modified in the call. For this reason I wonder if there is a particular utility to keep it as non-fixed?

This would simplify this loop declaration:

https://github.com/grindery-io/grindery-nexus-connector-web3/blob/0b49a8bc310f4e1f03d5c4a6465991b55ef11ed4/src/utils.ts#L34

And also this condition that could be removed:
https://github.com/grindery-io/grindery-nexus-connector-web3/blob/0b49a8bc310f4e1f03d5c4a6465991b55ef11ed4/src/utils.ts#L40-L42

because `"parameters"` is associated to functions and `"parameterFilters"` to events but I'm not sure that such parameters can reside directly in `fields`.

**Comment by SAPikachu** [comment]
I remember that parameter was used at some point in the past, but probably deleted later. I would prefer to keep it as is, since the parameter is useful in some cases, and it won't complicate the logic too much.

**Comment by tcoratger** [comment]
@SAPikachu Ok no problem, let us close this then.
