### ISSUE TITLE
feat(`Gnosis`): question about Gnosis Safe API endpoint

### ISSUE THREAD

**Issue by tcoratger** [grindery-io/grindery-nexus-connector-web3#114]
Working with the web3 connector, I realized that the base URL for the Gnosis Safe API was `https://safe-client.gnosis.io/` in the codebase. 

https://github.com/grindery-io/grindery-nexus-connector-web3/blob/daaaca44607e26da68508ae69e69a7322e7e9f2a/src/web3/evm/connector/gnosisSafe/triggers/deposit.ts#L38

I wondered if there was some confusion here because I couldn't reproduce the GET `incoming-transfers` request for example with this address. So I went to check on the documentation and I found different URLs:
- Ethereum mainnet: https://safe-transaction-mainnet.safe.global/
- BSC mainnet: https://safe-transaction-bsc.safe.global/
- Polygon: https://safe-transaction-polygon.safe.global/

For example for Ethereum I got to execute the request with: `https://safe-transaction-mainnet.safe.global/api/v1/safes/{address}/incoming-transfers/`

Did I miss something there or maybe the URL has evolved since the implementation?

**Comment by SAPikachu** [comment]
We are not using the API documented at https://safe-transaction-mainnet.safe.global/ , instead we use the API used by their web UI https://app.safe.global/ as it has quite a few nice features that the documented API doesn't have. Specifically, try `https://safe-client.safe.global/v1/chains/5/safes/0xE547C45BabcE6B8b5A004AE1eF38AC8E26a7806d/incoming-transfers` for the `incoming-transfers` API. Note that its URL format is different.
