### ISSUE TITLE
feat(Gnosis): propose new transaction failure

### ISSUE THREAD

**Issue by tcoratger** [grindery-io/grindery-nexus-connector-web3#120]
In our Gnosis Safe logic, we have something to propose a new transaction using a call to the following endpoint of Gnosis Safe API: 
https://github.com/grindery-io/grindery-nexus-connector-web3/blob/0da5eead51e762887855d6b9407b9621cd832d03/src/web3/evm/gnosisSafe.ts#L135

As mentioned [here](https://github.com/grindery-io/grindery-nexus-connector-web3/pull/119), it seems that the base URL is in fact `https://safe-client.safe.global/` if I’m correct but even with this URL, I cannot get a proper result, always having a `422 Unprocessable Entity` error message. 

For example, when I call `https://safe-client.safe.global/v1/chains/5/transactions/{GnosisSafeAddress}/propose` with the following body: 
```JSON
{
  "origin": "Grindery Nexus",
  "safeTxHash": "0xd977d1ca04b8c6c552d4c4c74a4e3c98f8fb73a7075a700bfc31d002c1be5df9",
  "signature": "0x956d49e51984907bad58e3cfd15dc25fb87f5a3c5b3ff450bb315a9d3861031210773e61c927f516162ace7a7e7fa275c2ad0ab750a3bf7d06eb7c2b1b2a648e1c",
  "sender": "0xBe8C10Dbf4c6148f9834C56C3331f8191f355552",
  "to": "0xBe8C10Dbf4c6148f9834C56C3331f8191f355552",
  "value": "1",
  "data": "0x",
  "operation": 0,
  "safeTxGas": "0",
  "baseGas": "0",
  "gasPrice": "0",
  "gasToken": "0x0000000000000000000000000000000000000000",
  "refundReceiver": "0x0000000000000000000000000000000000000000",
  "nonce": "0"
}
```

It seems completely valid.
- I checked the associated Gnosis Safe function: https://github.com/safe-global/safe-client-gateway/blob/eb481938a49c29b979fe98a5577f719f42a2b2eb/src/routes/transactions/routes.rs#L204-L244
- I checked the data structure that should be provided: https://github.com/safe-global/safe-client-gateway/blob/eb481938a49c29b979fe98a5577f719f42a2b2eb/src/routes/transactions/models/requests.rs#L10-L55

Everything seems to be valid. I saw that this error is frequently obtained due to non checkSum addresses but here all the addresses are checkSum (can be verified [here](https://web3-tools.netlify.app/)). Have you ever encountered this problem or maybe I missed something in the middle?

**Comment by SAPikachu** [comment]
@tcoratger Have you added our wallet address as delegate of an owner? See https://github.com/grindery-io/grindery-nexus-connector-web3-microsite/blob/master/src/components/pages/GnosisSafePage.tsx for the logic. This is done in sign in process in Flow.

Also, have you confirmed that your nonce is correct?

**Comment by tcoratger** [comment]
@SAPikachu You are right, nonce issue due to a currently processing transaction :)
