### ISSUE TITLE
feat(connector): get a better typing for `ConnectorInput`

### ISSUE THREAD

**Issue by tcoratger** [grindery-io/grindery-nexus-connector-web3#72]
Now, `ConnectorInput` is a type defined by:
```typescript
export type ConnectorInput<T = unknown> = WebSocketPayloadCommon & {
  authentication?: string;
  fields: T;
};
```

The `unknown` type for the field `fields` can generate confusion and lots of additional typing struggles inside functions. Maybe it would be better to change this to more strict types.

I believe this also includes a change to the `ConnectorDefinition` type inside the `grindery-nexus-common-utils` repository.

**Comment by SAPikachu** [comment]
Good idea, I just updated `grindery-nexus-common-utils` to [allow more specific typing](https://github.com/grindery-io/grindery-nexus-common-utils/commit/b3dbe8afb029f48a4f8dca9a9d909b3d7e0f826a) in actions and triggers, we can use that in new code or refactor. :)
